name = "lean_to_lambdabox"
version = "0.1.0"
defaultTargets = ["LeanToLambdaBox", "lean_to_lambdabox"]

[[lean_lib]]
name = "LeanToLambdaBox"

[[lean_exe]]
name = "lean_to_lambdabox"
supportInterpreter = true
root = "Main"
