import Lean
import LeanToLambdaBox 
import LeanToLambdaBox.Printing

-- So that the binder names generated by quotation are unmangled by Lean's hygiene system, which makes for nicer printing
set_option hygiene false

def elab_term: Lean.Elab.TermElabM neterm := do
  let stx: Lean.Syntax ← `(fun n zero_case succ_case => @Nat.casesOn (fun m: Nat => Unit) n zero_case succ_case)
  let e ← Lean.Elab.Term.elabTerm stx .none
  Lean.Compiler.LCNF.CompilerM.run (Erasure.erase e)


unsafe def main: IO Unit := do
  Lean.enableInitializersExecution --probably necessary, see doc for Lean.importModules
  Lean.initSearchPath (← Lean.findSysroot)
  let imports: Array Lean.Import := #[`Init]
  let env ← Lean.importModules imports default (loadExts := true) (level := .exported)
  let corestate := Lean.Core.State.mk env default default default default default default default

  let (((t, _), _), _) ← elab_term.run.run.toIO {fileName := "", fileMap := default} corestate
  t |> Serialize.to_sexpr |> toString |> IO.println

