import Lean
import LeanToLambdaBox 
import LeanToLambdaBox.Printing

-- So that the binder names generated by quotation are unmangled by Lean's hygiene system, which makes for nicer printing
set_option hygiene false

def asdf: Lean.Elab.TermElabM Unit := do
  let stx: Lean.Syntax ← `(fun n zero_case succ_case => @Nat.casesOn (fun m: Nat => Unit) n zero_case succ_case)
  let e: Lean.Expr ← Lean.Elab.Term.elabTerm stx .none
  let t: neterm ← Lean.Compiler.LCNF.CompilerM.run (Erasure.erase e)
  let s: sexpr := Serialize.to_sexpr t
  IO.println s.toString

unsafe def main: IO Unit := do
  Lean.enableInitializersExecution --probably necessary, see doc for Lean.importModules
  Lean.initSearchPath (← Lean.findSysroot)
  let imports: Array Lean.Import := #[`Init]
  let env ← Lean.importModules imports default (loadExts := true) (level := .exported)
  let _ ← asdf.run.run.toIO {fileName := "", fileMap := default} (.mk env default default default default default default default)
