name = "from_lean_via_lean"

[[require]]
name = "from_lean_common"
path = ".."

[[lean_exe]]
name = "demo0"
main = "demo0"

[[lean_exe]]
name = "demo1"
main = "demo1"

[[lean_exe]]
name = "cube"
main = "cube"
